"""v380: one scale for the whole portrait (A_FOCUS_WEARS_GOLD too). All data is synthetic.

Owner observation (2026-09-30), looking at v378 on his vault: "the intended
surface for Nostalgia is three times the radius of [my brother] ... the
biggest things would be my dad and my mom, to tell a story about myself ...
why is Forgiveness two or three times the size of Katie?" v378 calibrated
PER TYPE, so the best-told theme ("Family", tagged in nearly every source)
set every theme's target and themes outsized the people. v380 calibrates the
whole graph on ONE scale anchored on people (the best-told parent/spouse/
partner sits on its target) and sizes every other type with ``type_scale``
(theme 0.3 of a parent). Told can exceed target: ``over`` is emitted, the
drawing marks it, doctor lists the most over-told. v378's behaviour is one
config line away (``calibration.mode: per_type``) and reproduces its numbers
byte-for-byte (``goldens/portrait_targets_v378_per_type.json``, generated by
the v378 code on this same fixture).

Owner addition (same day): "a golden orb around the intended size" for the
entities picked to be focuses, and projects distinct — A_FOCUS_WEARS_GOLD:
a static gold halo outside the target ring on every active Focus, a
second-colour halo on every project, ``focus``/``project`` flags on nodes.

Fixture: the v378 real-shaped vault (``test_v378_the_ring_is_a_target``),
then a theme page, "Family", tagged by three classified sources.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SYSTEM = ROOT / "system"
TESTS = ROOT / "tests"
sys.path.insert(0, str(SYSTEM))
sys.path.insert(0, str(TESTS))

from tempdirs import root_parent_tmp  # noqa: E402
import portrait_targets  # noqa: E402
import serve_wiki  # noqa: E402
from test_v376_a_focus_finds_its_page import DRIVER, GRAPH, make_vault  # noqa: E402
from test_v378_the_ring_is_a_target import (  # noqa: E402
    BULK, CONVERSATION, PASSING, _classification, _source,
)

GOLDEN = TESTS / "goldens" / "portrait_targets_v378_per_type.json"
FAMILY_SOURCES = [f"sources/conversations/msg-00000000000000000000010{i}.md" for i in range(3)]


def build_v378_state(system: Path, vault: Path, run) -> None:
    """The v378 test's fixture, to its 'after' state (same steps, same order)."""
    run([sys.executable, "-c", DRIVER, str(system)])
    run([sys.executable, str(system / "wiki_compile.py"), "--no-ai"])
    _classification(vault, "answers/K1.md",
                    people=[{"name": "Mom", "relationship": "mother", "mention_count": 3}])
    _classification(vault, "answers/L1.md",
                    people=[{"name": "Katie", "relationship": "wife", "mention_count": 2}])
    _source(vault / CONVERSATION, "Talked about Mom's garden and her kindness.")
    _classification(vault, CONVERSATION,
                    people=[{"name": "Mom", "relationship": "mother", "mention_count": 2}])
    _source(vault / PASSING, "Drove past the old school; Mom used to say it was haunted.")
    _classification(vault, PASSING, places=[{"name": "Mesa", "type": "city"}])
    _source(vault / BULK, "Mom Mom Mom — a newsletter with her name in it.")
    roadmap_file = vault / "state" / "roadmap.json"
    roadmap = json.loads(roadmap_file.read_text(encoding="utf-8"))
    for focus in roadmap["focuses"]:
        if focus["id"] == "katie":
            focus["portrait_weight"] = 0.9
    roadmap_file.write_text(json.dumps(roadmap), encoding="utf-8")


def numbers(graph: dict) -> dict:
    """Every portrait number v378 emitted (the byte-for-byte comparison)."""
    return {
        "nodes": [{k: n[k] for k in ("id", "kind", "credit", "told", "target", "gap", "weight", "tier")}
                  for n in sorted(graph["nodes"], key=lambda n: n["id"])],
        "relationships": [{k: e[k] for k in ("page", "relation", "told", "goal", "gap")}
                          for e in sorted((e for e in graph["edges"] if e.get("kind") == "relationship"),
                                          key=lambda e: e["page"])],
        "calibration": graph["calibration"],
    }


def _runner(vault: Path, cwd: Path):
    env = dict(os.environ, LIFEHUG_VAULT_ROOT=str(vault))

    def run(args: list[str]) -> str:
        proc = subprocess.run(args, capture_output=True, text=True, env=env, cwd=str(cwd))
        if proc.returncode != 0:
            raise AssertionError(f"{args[:3]} failed:\n{proc.stdout}\n{proc.stderr}")
        return proc.stdout
    return run


def _graph(run, system: Path) -> dict:
    out = run([sys.executable, "-c", GRAPH, str(system)])
    return json.loads(out.strip().splitlines()[-1])["graph"]


def _override(vault: Path, data: dict | None) -> None:
    path = vault / "state" / "portrait_targets.json"
    if data is None:
        path.unlink(missing_ok=True)
    else:
        path.write_text(json.dumps(data), encoding="utf-8")


DOCTOR = ("import sys; sys.path.insert(0, sys.argv[1]); import lifehug; "
          "lifehug.graph_portrait_checks()")


class OneScaleTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls._holder = unittest.TestCase()
        cls.tmp = root_parent_tmp(cls._holder, ROOT, prefix="lifehug-v380-")
        cls.vault = make_vault(cls.tmp / "vault")
        run = _runner(cls.vault, cls.tmp)
        build_v378_state(SYSTEM, cls.vault, run)
        _override(cls.vault, {"calibration": {"mode": "per_type"}})
        cls.per_type = _graph(run, SYSTEM)
        _override(cls.vault, None)
        cls.shared = _graph(run, SYSTEM)
        # A theme the classifier tags in almost every source: "Family".
        page = cls.vault / "wiki" / "themes" / "family.md"
        page.parent.mkdir(parents=True, exist_ok=True)
        sources = "\n".join(f'  - "{s}"' for s in FAMILY_SOURCES)
        page.write_text(f'---\ntitle: "Family"\ntype: "theme"\nsources:\n{sources}\n---\n\n# Family\n',
                        encoding="utf-8")
        for src in FAMILY_SOURCES:
            _source(cls.vault / src, "Sunday dinner with everyone.")
            _classification(cls.vault, src, themes=["Family"])
        cls.themed = _graph(run, SYSTEM)
        cls.doctor = run([sys.executable, "-c", DOCTOR, str(SYSTEM)])
        _override(cls.vault, {"type_scale": {"theme": 0.15},
                              "drawing": {"focus_halo": {"color": "#aa0000"}}})
        cls.overridden = _graph(run, SYSTEM)
        cls.doctor_override = run([sys.executable, "-c", DOCTOR, str(SYSTEM)])
        _override(cls.vault, None)

    @classmethod
    def tearDownClass(cls):
        cls._holder.doCleanups()

    @staticmethod
    def node(graph: dict, page: str) -> dict:
        return next(n for n in graph["nodes"] if n["id"] == page)

    # --- one scale ---------------------------------------------------------
    def test_shared_is_the_default_and_a_parent_or_spouse_anchors_it(self):
        self.assertEqual(portrait_targets.CALIBRATION_MODE, "shared")
        self.assertEqual(self.shared["calibration_mode"], "shared")
        anchor = self.shared["anchor"]
        self.assertEqual(anchor["source"], "anchor")
        self.assertIn(anchor["kind"], portrait_targets.ANCHOR_KINDS)
        best = self.node(self.shared, anchor["id"])
        self.assertAlmostEqual(best["told"], best["target"], places=2)
        self.assertEqual(best["gap"], 0)
        # The best-told anchor member: no parent/spouse/partner is told past its target.
        for n in self.shared["nodes"]:
            if n["type"] == "people" and n["kind"] in portrait_targets.ANCHOR_KINDS:
                self.assertEqual(n["over"], 0, n["id"])

    def test_mom_the_parent_anchors_the_fixture(self):
        self.assertEqual(self.shared["anchor"]["id"], "wiki/people/mom.md")
        self.assertEqual(self.shared["anchor"]["kind"], "parent")

    def test_every_type_scale_is_type_scale_times_the_anchor(self):
        a = self.themed["anchor"]["scale"]
        for etype, row in self.themed["calibration"].items():
            self.assertAlmostEqual(row["scale"], portrait_targets.type_scale(
                portrait_targets.load(None), etype) * a, places=3, msg=etype)

    def test_a_theme_target_is_three_tenths_of_a_parent(self):
        mom = self.node(self.themed, "wiki/people/mom.md")
        family = self.node(self.themed, "wiki/themes/family.md")
        self.assertEqual(family["kind"], "theme")
        # Same table weight (1.0) and no Focus tier on the theme: undo Mom's tier.
        parent_unit = mom["target"] / (mom["weight"] * portrait_targets.TIER_BASIC)
        self.assertAlmostEqual(family["target"] / parent_unit, portrait_targets.TYPE_SCALE_THEME, places=2)
        self.assertEqual(portrait_targets.TYPE_SCALE_THEME, 0.3)

    def test_over_told_is_emitted(self):
        family = self.node(self.themed, "wiki/themes/family.md")
        self.assertGreater(family["told"], family["target"])
        self.assertAlmostEqual(family["over"], family["told"] / family["target"] - 1, places=2)
        self.assertEqual(family["gap"], 0)
        for n in self.themed["nodes"]:
            self.assertAlmostEqual(n["over"], max(0.0, n["told"] / n["target"] - 1), places=2)
        for e in self.themed["edges"]:
            if e.get("kind") == "relationship":
                self.assertIn("over", e)

    def test_doctor_lists_the_most_over_told_beside_the_gaps(self):
        self.assertIn("graph portrait gaps (largest 10 per type", self.doctor)
        self.assertIn("graph portrait over-told (most 10 per type", self.doctor)
        over = self.doctor.split("graph portrait over-told", 1)[1]
        self.assertIn("  themes:", over)
        self.assertIn("Family (theme)", over)
        self.assertIn("graph portrait calibration: shared - one scale", self.doctor)
        self.assertIn("set by Mom (parent) [anchor]", self.doctor)
        self.assertIn("type_scale.theme = 0.3 <- framework", self.doctor)
        self.assertIn('calibration.mode = "shared" <- framework', self.doctor)

    # --- per_type keeps v378 ------------------------------------------------
    def test_per_type_reproduces_v378_byte_for_byte(self):
        golden = GOLDEN.read_text(encoding="utf-8")
        self.assertEqual(json.dumps(numbers(self.per_type), indent=2, sort_keys=True) + "\n", golden)
        self.assertEqual(self.per_type["calibration_mode"], "per_type")
        self.assertNotIn("anchor", self.per_type)

    # --- vault override ----------------------------------------------------
    def test_vault_type_scale_theme_takes_effect_and_doctor_shows_origin(self):
        before = self.node(self.themed, "wiki/themes/family.md")["target"]
        after = self.node(self.overridden, "wiki/themes/family.md")["target"]
        self.assertAlmostEqual(after, before / 2, places=2)
        self.assertIn("type_scale.theme = 0.15 <- vault state/portrait_targets.json", self.doctor_override)

    # --- drawing ------------------------------------------------------------
    def test_radius_comes_from_the_target_and_the_fill_is_capped(self):
        style = self.themed["style"]
        self.assertEqual(style["value_max"], round(max(n["target"] for n in self.themed["nodes"]), 3))
        self.assertEqual(style["over_ring_offset"], portrait_targets.OVER_RING_OFFSET)
        body = serve_wiki.view_graph()[1]
        self.assertIn("n.ringR = radius(n.target)", body)
        self.assertIn("Math.min(radius(n.told), n.ringR)", body)
        self.assertIn("n.overR", body)
        self.assertIn("one scale for the whole portrait", body)
        self.assertIn("told past its target", body)

    # --- A_FOCUS_WEARS_GOLD -------------------------------------------------
    def test_a_focus_carries_the_flag_and_a_non_focus_does_not(self):
        self.assertIs(self.node(self.themed, "wiki/people/mom.md")["focus"], True)
        self.assertEqual(self.node(self.themed, "wiki/people/mom.md")["focus_label"], "Mom")
        self.assertIs(self.node(self.themed, "wiki/themes/family.md")["focus"], False)
        self.assertNotIn("focus_label", self.node(self.themed, "wiki/themes/family.md"))
        projects = [n for n in self.themed["nodes"] if n["type"] == "projects"]
        self.assertTrue(projects)
        for n in self.themed["nodes"]:
            self.assertIs(n["project"], n["type"] == "projects", n["id"])

    def test_the_svg_draws_a_gold_halo_for_a_focus_only(self):
        style = self.themed["style"]
        self.assertEqual(style["focus_halo"]["color"], portrait_targets.FOCUS_HALO_COLOR)
        self.assertEqual(style["project_halo"]["color"], portrait_targets.PROJECT_HALO_COLOR)
        body = serve_wiki.view_graph()[1]
        self.assertIn("n.focusR = n.focus ?", body)
        self.assertIn("'class': 'focus-halo'", body)
        self.assertIn("n.projectR = n.project ?", body)
        self.assertIn("'class': 'project-halo'", body)
        self.assertIn("Gold halo = an active Focus", body)
        self.assertIn("Project halo = a project", body)
        self.assertNotIn("stroke-dasharray", body.split("'class': 'focus-halo'")[1].split("});")[0])
        self.assertNotIn("animate", body.lower().split("'class': 'focus-halo'")[1].split("});")[0])

    def test_a_focus_not_in_an_active_phase_wears_no_gold(self):
        vault = self.vault
        run = _runner(vault, self.tmp)
        roadmap_file = vault / "state" / "roadmap.json"
        original = roadmap_file.read_text(encoding="utf-8")
        roadmap = json.loads(original)
        for focus in roadmap["focuses"]:
            if focus["id"] == "mom":
                focus["phase"] = "maintenance"
        roadmap_file.write_text(json.dumps(roadmap), encoding="utf-8")
        try:
            graph = _graph(run, SYSTEM)
        finally:
            roadmap_file.write_text(original, encoding="utf-8")
        mom = self.node(graph, "wiki/people/mom.md")
        self.assertIs(mom["focus"], False)
        self.assertEqual(mom["focus_label"], "Mom")

    def test_config_override_changes_the_halo_colour(self):
        self.assertEqual(self.overridden["style"]["focus_halo"]["color"], "#aa0000")
        self.assertIn('drawing.focus_halo.color = "#aa0000" <- vault', self.doctor_override)
        self.assertIn(f'drawing.project_halo.color = "{portrait_targets.PROJECT_HALO_COLOR}" <- framework',
                      self.doctor_override)


class ConfigValidationTests(unittest.TestCase):
    def setUp(self):
        self.tmp = root_parent_tmp(self, ROOT, prefix="lifehug-v380-cfg-")

    def write(self, data: dict) -> portrait_targets.PortraitConfig:
        (self.tmp / "portrait_targets.json").write_text(json.dumps(data), encoding="utf-8")
        return portrait_targets.load(self.tmp)

    def test_new_keys_accept_good_values(self):
        cfg = self.write({
            "calibration": {"mode": "per_type",
                            "anchor": {"type": "person", "kinds": ["parent"], "quantile": 0.9}},
            "type_scale": {"theme": 0.2, "pet": 0.4},
            "drawing": {"over_ring_offset": 4,
                        "focus_halo": {"color": "#112233", "width": 4, "phases": ["active", "finishing"]},
                        "project_halo": {"color": "#445566", "opacity": 0.5}},
            "doctor": {"over_rows_per_type": 5},
        })
        self.assertEqual(cfg.errors, [])
        self.assertEqual(portrait_targets.type_scale(cfg, "pet"), 0.4)
        self.assertEqual(portrait_targets.type_scale(cfg, "unlisted"), 1.0)
        self.assertEqual(cfg.get("calibration.mode"), "per_type")

    def test_bad_values_reject_the_whole_override(self):
        cfg = self.write({
            "calibration": {"mode": "global",
                            "anchor": {"type": "dog", "kinds": [""], "quantile": 0}},
            "type_scale": {"theme": -0.3, "deep.nested": 1},
            "drawing": {"focus_halo": {"color": "gold", "phases": ["someday"], "opacity": 2},
                        "project_halo": {"color": "#12345"}},
        })
        joined = " ".join(cfg.errors)
        for key in ("calibration.mode", "calibration.anchor.type", "calibration.anchor.kinds",
                    "calibration.anchor.quantile", "type_scale.theme", "type_scale.deep.nested",
                    "drawing.focus_halo.color", "drawing.focus_halo.phases",
                    "drawing.focus_halo.opacity", "drawing.project_halo.color"):
            self.assertIn(key, joined)
        self.assertEqual(portrait_targets.type_scale(cfg, "theme"), portrait_targets.TYPE_SCALE_THEME)
        self.assertEqual(cfg.get("calibration.mode"), "shared")


class SharedCalibrationUnitTests(unittest.TestCase):
    def cfg(self):
        return portrait_targets.load(None)

    def test_one_anchor_sizes_every_type(self):
        rows = [
            {"id": "dad", "type": "person", "kind": "parent", "credit": 10.0, "base": 1.0},
            {"id": "kid", "type": "person", "kind": "child", "credit": 30.0, "base": 1.0},
            {"id": "me", "type": "person", "kind": "owner", "credit": 99.0, "base": 1.0},
            {"id": "fam", "type": "theme", "kind": "theme", "credit": 12.0, "base": 1.0},
            {"id": "home", "type": "place", "kind": "residence", "credit": 3.0, "base": 1.0},
        ]
        cal = portrait_targets.apply_targets(rows, self.cfg())
        self.assertEqual(cal["person"], {"scale": 10.0, "source": "anchor"})
        self.assertAlmostEqual(cal["theme"]["scale"], 3.0)
        self.assertAlmostEqual(cal["place"]["scale"], 6.0)
        self.assertEqual(rows[0]["gap"], 0.0)
        self.assertAlmostEqual(rows[1]["over"], 2.0)  # a child told past a parent's target
        self.assertAlmostEqual(rows[3]["over"], 3.0)  # Family: 12 told on a 3.0 target
        self.assertAlmostEqual(rows[4]["gap"], 0.5)

    def test_no_credited_anchor_falls_back_to_everything(self):
        rows = [
            {"type": "person", "kind": "friend", "credit": 2.0, "base": 0.5},
            {"type": "theme", "kind": "theme", "credit": 0.6, "base": 1.0},
        ]
        anchor = portrait_targets.calibration_anchor(rows, self.cfg())
        self.assertEqual(anchor["source"], "fallback")
        self.assertAlmostEqual(anchor["scale"], 4.0)
        self.assertEqual(portrait_targets.calibration_anchor([], self.cfg())["source"], "default")

    def test_per_type_mode_is_the_v378_function(self):
        cfg = self.cfg()
        cfg.values["calibration"]["mode"] = "per_type"
        rows = [
            {"type": "person", "kind": "parent", "credit": 4.0, "base": 1.0},
            {"type": "person", "kind": "sibling", "credit": 2.0, "base": 0.8},
            {"type": "theme", "kind": "theme", "credit": 30.0, "base": 1.0},
            {"type": "theme", "kind": "theme", "credit": 3.0, "base": 1.0},
        ]
        cal = portrait_targets.apply_targets(rows, cfg)
        self.assertEqual(cal["person"], {"scale": 4.0, "source": "own"})
        self.assertEqual(cal["theme"], {"scale": 30.0, "source": "own"})


if __name__ == "__main__":
    unittest.main()
