#!/usr/bin/env python3
"""Lifehug — Update Manager

Checks for, applies, and rolls back framework updates from the upstream repo.
User data (answers/, outputs/, sources/, question-bank.md, planner/source state) is never touched.

Usage:
    python3 system/update.py --check              # JSON: current, latest, update_available,
                                                    # changelog, main_version, available_version,
                                                    # tag_lapse, diagnostic
    python3 system/update.py --check --quiet       # Exit code only (0=current, 1=update available)
    python3 system/update.py --apply               # Apply latest version
    python3 system/update.py --apply --version N   # Apply specific version
    python3 system/update.py --rollback            # Revert to previous version
    python3 system/update.py --migrate-vault       # Repair a pre-v120 vault in place

--check compares BOTH the latest vN tag and origin/main's system/version.json
(lifehug#84): `latest` keeps its pre-existing, tags-only meaning (backward
compatible); the additive `available_version` is max(latest, main_version)
— the true latest, tags OR main. If main is ahead of the latest tag, that
IS a tag-lapse — the exact failure mode that let v118-v128 ship invisibly
for four days — and update_available/diagnostic report it off
available_version instead of being blind to it. A network failure or
missing remote degrades to the tags-only behavior, silently. --check
(quiet or not) caches its result to state/update_check.json; --apply/
--rollback refresh that cache's `current` so the update card never
announces an update that was just installed, and --apply additionally
caches the changelogs it crossed to state/last_update.json. All of this is
cached under the VAULT root (--vault-root / LIFEHUG_VAULT_ROOT / this
checkout, same precedence as --migrate-vault) so the wiki viewer's
vault-rooted STATE_DIR reads what --check/--apply just wrote, in the
external layout too.
"""

import argparse
import json
import os
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

SYSTEM_DIR = Path(__file__).parent
REPO_DIR = SYSTEM_DIR.parent
VERSION_FILE = SYSTEM_DIR / "version.json"

# Files that are never overwritten by updates (user data)
PROTECTED_FILES = {
    "system/question-bank.md",
    "system/rotation.json",
    "system/coverage.json",
    "system/schedule.json",
    "config.yaml",
    "README.md",
    # Compiled user output / activity log — regenerated by `compile`, never framework-owned.
    "wiki/index.md",
    "wiki/log.md",
    "answers/",
    "outputs/",
    "sources/",
    "sources/manual/",
    "sources/artifacts/",
    "state/question_candidates.json",
    "state/question_queue.json",
    "state/planner_state.json",
    "state/source_manifest.json",
    "state/source_lint_findings.json",
    "state/focus_recommendations.json",
    "state/" + ("spot" "light") + "_recommendations.json",
    # Legacy paths (pre-v8) — still protected so historical content isn't clobbered
    "drafts/",
    ("spot" "lights") + "/",
}


def load_json(path):
    with open(path) as f:
        return json.load(f)


def save_json(path, data):
    with open(path, "w") as f:
        json.dump(data, f, indent=2)
        f.write("\n")


def run_git(*args, check=True):
    """Run a git command in the repo directory and return stripped stdout.

    Suitable for git plumbing whose output is a token/list (tags, remotes,
    version numbers). Do NOT use for extracting file content — stripping would
    drop the file's trailing newline. Use read_repo_file_at for that.
    """
    result = subprocess.run(
        ["git", "-C", str(REPO_DIR)] + list(args),
        capture_output=True, text=True, check=check,
    )
    return result.stdout.strip()


def read_repo_file_at(ref, filepath):
    """Return the exact bytes of a file at a git ref, preserving trailing
    newlines (unlike run_git, which strips). Raises CalledProcessError if the
    path does not exist at that ref."""
    result = subprocess.run(
        ["git", "-C", str(REPO_DIR), "show", f"{ref}:{filepath}"],
        capture_output=True, check=True,
    )
    return result.stdout  # bytes


def repo_file_is_executable_at(ref, filepath):
    """True if the file's git mode at the ref is executable (100755).
    Path.write_bytes creates NEW files as 0o644, so without this the updater
    ships executable framework scripts (e.g. file_answer_bg.sh) without their
    exec bit. Returns False on any git error — mode sync is best-effort."""
    result = subprocess.run(
        ["git", "-C", str(REPO_DIR), "ls-tree", ref, "--", filepath],
        capture_output=True, text=True,
    )
    if result.returncode != 0 or not result.stdout.strip():
        return False
    return result.stdout.split(None, 1)[0] == "100755"


def is_protected(filepath):
    """True if filepath is user data the updater must never overwrite.

    Directory entries in PROTECTED_FILES (those ending in '/') protect
    everything beneath them; file entries match exactly. Exact matching for
    files avoids the prefix trap where 'config.yaml' would also shadow
    'config.yaml.example'."""
    for p in PROTECTED_FILES:
        if p.endswith("/"):
            if filepath == p.rstrip("/") or filepath.startswith(p):
                return True
        elif filepath == p:
            return True
    return False


# ---------------------------------------------------------------------------
# v120 durable-data contract migration
#
# v120 introduced system/vault_contract.json and made rotation, coverage and
# question_bank BLOCKING-required at vault bind time: every entry point that
# imports lifehug_core calls resolve_vault_root(), which calls
# validate_minimum_vault_shape(), which rejects the whole vault if a required
# JSON file is absent, carries an unsupported `version`, or is missing any of
# the contract's `required_keys`.
#
# Nothing repaired vaults written by <= v119. An external user applying
# v116 -> v128 in one hop therefore ended up with new code that refuses to
# read their own vault ("vault rotation has an unsupported schema version").
# The founder's vault dodged it only because its state files grew a key at a
# time through every intermediate release.
#
# This migration reads the target version's own contract and brings the vault
# up to it: additive, idempotent, and never destructive.
# ---------------------------------------------------------------------------

# Honest defaults for contract-required keys a pre-v120 vault may lack. The
# KEY SET is always derived from vault_contract.json — this table only supplies
# the framework's own meaning for keys it already knows, so a repaired vault
# behaves exactly like a fresh one rather than like an arbitrary zero value.
V120_KEY_DEFAULTS = {
    "rotation": {
        # Passes are 1-indexed everywhere (`pass_names[current_pass - 1]`).
        "current_pass": 1,
        # The framework's own inline fallback in ask.py / gen_followups.py.
        "pass_names": ["skeleton", "depth", "connections", "polish"],
        # "not recorded" — the contract types these string|null for this reason.
        "last_question_id": None,
        "last_asked_at": None,
        "next_question_id": None,
        # Counters restart from a truthful zero; `rebuild_state.py` recomputes
        # them from the question bank on the next run.
        "questions_asked": 0,
        "questions_answered": 0,
        # ask.py's own default when the key is absent.
        "focus_frequency": 4,
    },
    "coverage": {
        "last_updated": None,
        # Empty until rebuild_coverage() derives it from the question bank —
        # the same state a freshly initialised vault is in.
        "categories": {},
    },
}

# Pre-v21 spellings the contract key replaced. Adopting the legacy VALUE here
# (and dropping the stale key) keeps the user's setting and stops the v21
# Focus-terminology migration from later renaming the old key on top of the
# default we just wrote.
V120_LEGACY_KEY_ALIASES = {
    "focus_frequency": ("spot" "light_frequency",),
}

# Mirrors vault_paths._schema_value_matches — kept local so the migration can
# run against a vault the framework's own loader still refuses to bind.
_V120_TYPE_CHECKS = {
    "null": lambda v: v is None,
    "string": lambda v: isinstance(v, str),
    "integer": lambda v: isinstance(v, int) and not isinstance(v, bool),
    "number": lambda v: isinstance(v, (int, float)) and not isinstance(v, bool),
    "boolean": lambda v: isinstance(v, bool),
    "array": lambda v: isinstance(v, list),
    "object": lambda v: isinstance(v, dict),
}

_V120_TYPE_FALLBACKS = {
    "null": None,
    "string": "",
    "integer": 0,
    "number": 0,
    "boolean": False,
    "array": [],
    "object": {},
}


def _v120_matches_type(value, expected):
    """True if value satisfies a contract type spec such as 'string|null'."""
    if not isinstance(expected, str):
        return True
    return any(_V120_TYPE_CHECKS.get(option, lambda _v: False)(value)
               for option in expected.split("|"))


def _v120_type_fallback(expected):
    """A safe value for a contract key this migration has no opinion about.

    Prefers null when the contract allows it (the honest "unset"), otherwise
    the empty value of the first accepted type.
    """
    options = expected.split("|") if isinstance(expected, str) else []
    if "null" in options:
        return None
    for option in options:
        if option in _V120_TYPE_FALLBACKS:
            return _V120_TYPE_FALLBACKS[option]
    return None


def load_vault_contract(repo_dir=None):
    """Load the vault contract that governs the vault being migrated.

    Prefers the copy inside the vault (apply_version has just written the
    TARGET version's contract there) and falls back to the running framework's
    own copy. Returns None when neither is readable — a pre-v120 target has no
    contract and needs no migration.
    """
    repo = Path(repo_dir) if repo_dir else REPO_DIR
    for candidate in (repo / "system" / "vault_contract.json",
                      SYSTEM_DIR / "vault_contract.json"):
        try:
            value = json.loads(candidate.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            continue
        if isinstance(value, dict) and isinstance(value.get("data_paths"), dict):
            return value
    return None


def _v120_vault_layout(repo_dir):
    """'embedded' when the framework ships inside the vault, else 'external'.

    The contract forbids `system/` in an external vault, so its presence is the
    layout discriminator — and it decides whether rotation lives at
    system/rotation.json (embedded) or state/rotation.json (external).
    """
    return "embedded" if (repo_dir / "system").is_dir() else "external"


def _v120_contract_path(repo_dir, entry, layout):
    relative = entry.get("embedded_path") if layout == "embedded" else entry.get("path")
    relative = relative or entry.get("path")
    if not isinstance(relative, str) or not relative:
        return None
    candidate = Path(relative)
    if candidate.is_absolute() or ".." in candidate.parts:
        return None
    return repo_dir / candidate


def _v120_required_json_shape(name, entry):
    """Return (required_keys, supported_versions, version_field) or None.

    Only blocking-validated JSON entries need migrating; everything else the
    binder treats as opaque or deferred.
    """
    schema = entry.get("schema")
    if not isinstance(schema, dict) or schema.get("format") != "json":
        return None
    if schema.get("validation_policy") != "blocking":
        return None
    required = schema.get("required_keys")
    if not isinstance(required, dict):
        required = {}
    supported = schema.get("supported")
    if not isinstance(supported, list):
        supported = schema.get("supported_versions")
    if not isinstance(supported, list):
        supported = []
    version_field = schema.get("version_field")
    return required, supported, version_field


def _v120_migrate_json_file(name, path, required, supported, version_field):
    """Bring one required JSON file up to the contract. Returns True if changed.

    Additive by construction: existing keys keep their position and value. A
    value that would fail validation is REPLACED but never lost — the original
    is preserved alongside under `legacy_<key>`, which the contract permits
    (`unknown_fields: allow`).
    """
    defaults = V120_KEY_DEFAULTS.get(name, {})
    data = None
    if path.exists():
        salvageable = False
        try:
            loaded = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            # Unreadable or corrupt (e.g. an interrupted write) — the most
            # common real-world reason a vault won't bind. Never repairable
            # in place, ALWAYS salvaged before rebuild.
            loaded = None
            salvageable = True
        if isinstance(loaded, dict):
            data = loaded
        elif loaded is not None:
            # A non-object payload cannot be repaired in place either.
            salvageable = True
        if salvageable:
            # Keep the user's original bytes beside the rebuilt file rather
            # than discarding them — corrupt or not, they're not ours to lose.
            salvage = path.with_name(path.name + ".pre-v120")
            if not salvage.exists():
                try:
                    salvage.write_bytes(path.read_bytes())
                except OSError:
                    raise RuntimeError(
                        f"cannot salvage {path.name} before rebuilding it — "
                        "refusing to overwrite the original"
                    ) from None
    if data is None:
        data = {}

    before = json.dumps(data, sort_keys=True)

    # 1. Schema version: the blocker behind "unsupported schema version".
    if version_field and supported:
        if data.get(version_field) not in supported:
            if version_field in data:
                data.setdefault(f"legacy_{version_field}", data[version_field])
            data[version_field] = supported[-1]

    # 2. Every other contract-required key.
    for key, expected in required.items():
        if key == version_field:
            continue
        if key in data and _v120_matches_type(data[key], expected):
            continue
        if key in data:
            # Present but the wrong type — park the original, then replace.
            original = data.pop(key)
            if f"legacy_{key}" not in data:
                data[f"legacy_{key}"] = original
        replacement = None
        for alias in V120_LEGACY_KEY_ALIASES.get(key, ()):
            if alias in data and _v120_matches_type(data[alias], expected):
                replacement = data.pop(alias)
                break
        if replacement is None:
            replacement = defaults[key] if key in defaults else _v120_type_fallback(expected)
            if not _v120_matches_type(replacement, expected):
                replacement = _v120_type_fallback(expected)
        data[key] = json.loads(json.dumps(replacement))  # never share mutables

    if path.exists() and json.dumps(data, sort_keys=True) == before:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    save_json(path, data)
    return True


def migrate_vault_to_v120(repo_dir=None):
    """Upgrade a pre-v120 vault in place to the v120 durable-data contract.

    Idempotent: running it on a vault that already satisfies the contract
    changes nothing and returns an empty list. Returns the vault-relative paths
    it rewrote or created.
    """
    repo = Path(repo_dir) if repo_dir else REPO_DIR
    contract = load_vault_contract(repo)
    if contract is None:
        return []
    data_paths = contract.get("data_paths") or {}
    required_names = contract.get("required_data_paths") or []
    layout = _v120_vault_layout(repo)
    changed = []

    for name in required_names:
        entry = data_paths.get(name)
        if not isinstance(entry, dict):
            continue
        path = _v120_contract_path(repo, entry, layout)
        if path is None:
            continue
        if entry.get("kind") == "directory":
            if not path.is_dir():
                path.mkdir(parents=True, exist_ok=True)
                changed.append(path.relative_to(repo).as_posix())
            continue
        # The state/ (external) or system/ (embedded) parent must exist before
        # the binder can even open the file.
        path.parent.mkdir(parents=True, exist_ok=True)
        shape = _v120_required_json_shape(name, entry)
        if shape is None:
            # Opaque required file (question_bank). Never synthesised from
            # nothing — a vault without its question bank is not a Lifehug
            # vault — but a stale upstream copy is a legitimate seed.
            if not path.exists():
                seed = repo / "system" / "question-bank-upstream.md"
                if name == "question_bank" and seed.exists():
                    path.write_bytes(seed.read_bytes())
                    changed.append(path.relative_to(repo).as_posix())
            continue
        required, supported, version_field = shape
        if _v120_migrate_json_file(name, path, required, supported, version_field):
            changed.append(path.relative_to(repo).as_posix())

    return changed


def find_upstream_remote():
    """Find the remote pointing to the lifehug upstream repo.

    Prefers a remote named 'upstream', falls back to 'origin',
    then any remote whose URL contains 'lifehug/lifehug'.
    """
    try:
        output = run_git("remote", "-v")
    except subprocess.CalledProcessError:
        return None

    remotes = {}
    for line in output.splitlines():
        parts = line.split()
        if len(parts) >= 2:
            remotes[parts[0]] = parts[1]

    # Prefer 'upstream' only when it points to the framework repo.
    if "upstream" in remotes and "lifehug/lifehug" in remotes["upstream"]:
        return "upstream"

    # Check if any remote URL contains lifehug/lifehug
    for name, url in remotes.items():
        if "lifehug/lifehug" in url:
            return name

    # In the framework repo itself, origin is acceptable when it is the framework.
    if "origin" in remotes and "lifehug/lifehug" in remotes["origin"]:
        return "origin"

    return None


def get_local_version():
    """Read the local version number from version.json."""
    if not VERSION_FILE.exists():
        return 0
    data = load_json(VERSION_FILE)
    return data.get("version", 0)


def fetch_tags(remote):
    """Fetch tags from the remote."""
    run_git("fetch", remote, "--tags", "--quiet", check=False)


def get_remote_main_info(remote):
    """Read {"version", "changelog"} from the remote's main branch version.json.

    This is the tag-lapse detector (lifehug#84): v118-v128 shipped on main
    while tagging silently stopped, so a tags-only check kept reporting
    "current: 117, latest: 117" for four days of real releases. Comparing
    against main directly notices that failure mode instead of being blind
    to it.

    Network-failure tolerant by design: a missing remote, an offline fetch,
    a main branch without the expected ref, or an unparsable version.json
    all fall through to None so callers degrade to tags-only, silently —
    this must never turn a network hiccup into a false diagnostic or a
    crash.
    """
    if not remote:
        return None
    run_git("fetch", remote, "main", "--quiet", check=False)
    try:
        content = read_repo_file_at(f"{remote}/main", "system/version.json")
        data = json.loads(content)
    except (subprocess.CalledProcessError, ValueError, OSError):
        return None
    version = data.get("version")
    if not isinstance(version, int) or isinstance(version, bool):
        return None
    return {"version": version, "changelog": data.get("changelog")}


def resolve_state_vault_root(args=None):
    """Where the per-vault update-check cache lives: the SAME precedence
    cmd_migrate_vault already uses — --vault-root (when the invoked
    subcommand accepts it) -> LIFEHUG_VAULT_ROOT -> this framework checkout
    (REPO_DIR).

    update.py's own REPO_DIR is the FRAMEWORK checkout (SYSTEM_DIR.parent) —
    correct for git operations (tags, commits) but wrong for state/*.json in
    the documented external layout, where the framework is installed
    separately from the vault. Writing the cache to REPO_DIR there would
    leave it somewhere serve_wiki.py's vault-rooted STATE_DIR never reads,
    silently inerting the whole feature. This must match lifehug_core's
    resolve_vault_root precedence for embedded installs (where the two
    roots are the same directory anyway) as well as external ones.
    """
    root = getattr(args, "vault_root", None) if args is not None else None
    root = root or os.environ.get("LIFEHUG_VAULT_ROOT")
    return Path(root).expanduser() if root else REPO_DIR


def _update_state_dir(args=None):
    # parents=False: the vault root itself must already exist — a typo'd
    # --vault-root/LIFEHUG_VAULT_ROOT must not silently grow a directory
    # tree and cache into it. Missing root -> FileNotFoundError, which every
    # caller's try/except treats as "skip caching", keeping writes best-effort.
    state_dir = resolve_state_vault_root(args) / "state"
    state_dir.mkdir(parents=False, exist_ok=True)
    return state_dir


def write_update_check_state(result, args=None):
    """Persist the most recent --check result to state/update_check.json so
    the viewer (serve_wiki.py's Loop view + home hub card) can show update
    status without running git on every page load. Best-effort: a write
    failure must never break --check itself."""
    try:
        payload = dict(result)
        payload["checked_at"] = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        save_json(_update_state_dir(args) / "update_check.json", payload)
    except OSError:
        pass


def write_last_update_state(from_version, to_version, crossed, args=None):
    """Persist the changelogs crossed by an --apply so the viewer can render
    a 'what changed' line for the most recent update (lifehug#84 item 4).
    Best-effort: a write failure must never fail the update itself."""
    try:
        save_json(_update_state_dir(args) / "last_update.json", {
            "applied_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
            "from_version": from_version,
            "to_version": to_version,
            "crossed": crossed,
        })
    except OSError:
        pass


def refresh_update_check_current(new_current, args=None):
    """After --apply/--rollback change the local version, the cached
    --check result's `current` (and derived `update_available`) must be
    refreshed too — otherwise the viewer's update card keeps announcing an
    update that was JUST installed until the next --check happens to run.
    Best-effort and a deliberate no-op when nothing is cached yet: an
    absent cache already renders as "unknown" in the viewer, never as
    stale-wrong, so there is nothing to correct."""
    try:
        path = _update_state_dir(args) / "update_check.json"
        data = load_json(path)
    except (OSError, ValueError):
        return
    if not isinstance(data, dict):
        return
    available_version = data.get("available_version")
    if not isinstance(available_version, int):
        latest = data.get("latest")
        available_version = latest if isinstance(latest, int) else None
    data["current"] = new_current
    if isinstance(available_version, int):
        data["update_available"] = available_version > new_current
    data["checked_at"] = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    try:
        save_json(path, data)
    except OSError:
        pass


def collect_crossed_changelogs(previous_version, target_version):
    """Changelog entries for every TAGGED version crossed by an apply, in
    ascending order — an apply can jump many releases in one hop (e.g.
    v117 -> v128), and the owner should see every changelog it crossed, not
    just the target's."""
    crossed = []
    for v in get_available_versions():
        if previous_version < v <= target_version:
            crossed.append({"version": v, "changelog": get_tag_changelog(v)})
    return crossed


def get_available_versions():
    """Get all version tags (vN format) sorted by version number."""
    try:
        output = run_git("tag", "-l", "v*")
    except subprocess.CalledProcessError:
        return []

    versions = []
    for tag in output.splitlines():
        tag = tag.strip()
        match = re.match(r"^v(\d+)$", tag)
        if match:
            versions.append(int(match.group(1)))

    return sorted(versions)


def get_latest_version():
    """Get the highest version number from tags."""
    versions = get_available_versions()
    return versions[-1] if versions else 0


def get_tag_changelog(version):
    """Read the changelog from a tag's annotation."""
    tag = f"v{version}"
    try:
        output = run_git("tag", "-l", "--format=%(contents)", tag)
        return output.strip() if output.strip() else None
    except subprocess.CalledProcessError:
        return None


def get_framework_files_from_tag(version):
    """Read the framework_files list from a specific version's version.json."""
    tag = f"v{version}"
    try:
        content = run_git("show", f"{tag}:system/version.json")
        data = json.loads(content)
        return data.get("framework_files", [])
    except (subprocess.CalledProcessError, json.JSONDecodeError):
        return None


def check_dirty_framework_files(framework_files):
    """Check if any framework files have uncommitted changes."""
    dirty = []
    try:
        status = run_git("status", "--porcelain")
    except subprocess.CalledProcessError:
        return []

    changed_files = set()
    for line in status.splitlines():
        if len(line) > 3:
            filepath = line[3:].strip()
            # Handle renames: "R  old -> new"
            if " -> " in filepath:
                filepath = filepath.split(" -> ")[-1]
            changed_files.add(filepath)

    for f in framework_files:
        if f in changed_files:
            dirty.append(f)

    return dirty


def run_migrations(target_version, current_version):
    """Run any one-time migrations needed for the target version.

    v8: legacy output folders are replaced by outputs/. We don't delete the
    legacy directories (they're protected user data), but we do ensure outputs/
    exists with a .gitkeep so compose.py can write to it.

    v12: unprompted story ingest and planner state need sources/manual/ and
    state/ to exist, but all actual source and planner files remain user data.
    """
    if target_version >= 8 and current_version < 8:
        outputs = REPO_DIR / "outputs"
        outputs.mkdir(exist_ok=True)
        gitkeep = outputs / ".gitkeep"
        if not gitkeep.exists():
            gitkeep.write_text("")
        legacy = []
        for name in ("drafts", "spot" "lights"):
            d = REPO_DIR / name
            if d.exists():
                # Check if it has any content beyond .gitkeep
                contents = [p for p in d.iterdir() if p.name != ".gitkeep"]
                if contents:
                    legacy.append(name)
        if legacy:
            print(
                f"  Note: legacy dirs still present with content: {', '.join(legacy)}.\n"
                f"  These were the pre-v8 deliverables location. New outputs go to outputs/.\n"
                f"  Move existing content to outputs/ at your leisure — nothing will overwrite it.",
            )

    if target_version >= 12 and current_version < 12:
        for directory in (REPO_DIR / "sources" / "manual", REPO_DIR / "sources" / "corrections", REPO_DIR / "state"):
            directory.mkdir(parents=True, exist_ok=True)
            gitkeep = directory / ".gitkeep"
            if not gitkeep.exists():
                gitkeep.write_text("")

    if target_version >= 22 and current_version < 22:
        directory = REPO_DIR / "sources" / "artifacts"
        directory.mkdir(parents=True, exist_ok=True)
        gitkeep = directory / ".gitkeep"
        if not gitkeep.exists():
            gitkeep.write_text("")

    if target_version >= 120 and current_version < 120:
        # v120: the durable-data contract became blocking at vault bind time.
        # Deliberately ordered BEFORE the v15/v21 blocks below: those import
        # framework modules (roadmap, focus_migration) that pull in
        # lifehug_core, which binds the vault at import time and would refuse
        # an unrepaired pre-v120 vault. Repair first, then those can run.
        try:
            changed = migrate_vault_to_v120()
        except Exception as exc:  # never let a migration break the update
            print(
                f"  Warning: v120 vault-contract migration failed: {exc}\n"
                f"  Your vault may not open until it is repaired. Re-run with:\n"
                f"    python3 system/update.py --migrate-vault",
                file=sys.stderr,
            )
        else:
            if changed:
                print(
                    f"  Migrated {len(changed)} durable-data file(s) to the v120 vault "
                    f"contract: {', '.join(changed)}.\n"
                    f"  Existing keys and values were preserved; only missing or "
                    f"unreadable contract keys were filled in."
                )

    if target_version >= 15 and current_version < 15:
        # v15: introduce the Focus/roadmap layer. This is a pure backfill —
        # the roadmap is *derived* from the existing question bank and answers.
        # No answers, no question-bank entries, and no outputs are touched.
        (REPO_DIR / "state").mkdir(parents=True, exist_ok=True)
        try:
            from roadmap import ROADMAP_FILE, rebuild_roadmap  # local import; same dir
            roadmap = rebuild_roadmap(write=True)
            print(
                f"  Derived roadmap of {len(roadmap['focuses'])} focuses → "
                f"state/{ROADMAP_FILE.name} (your answers and question bank were untouched)."
            )
        except Exception as exc:  # never let a migration break the update
            print(f"  Note: roadmap backfill deferred (run `python3 system/roadmap.py`): {exc}")

    if target_version >= 21 and current_version < 21:
        # v21: finish the Focus terminology migration across protected user
        # files. Older workspaces may still have question-bank sections,
        # rotation keys, queue groups, planner caps, or recommendation files
        # using pre-v21 terminology; normalize them without touching raw answers.
        try:
            from focus_migration import migrate_workspace  # local import; same dir
            changed = migrate_workspace()
            if changed:
                print(f"  Migrated Focus terminology in {len(changed)} protected file(s).")
        except Exception as exc:  # never let a migration break the update
            print(f"  Note: Focus terminology migration deferred (run `python3 system/focus_migration.py`): {exc}")

    if target_version >= 224 and current_version < 224:
        # v224: the entry-store flip (owner amendment 1, wave B item B3).
        # `state/landmarks.json` stops being a place anything is written by
        # hand and becomes a projection of the temporal claim substrate. Every
        # existing entry is promoted to a durable vault source and read into
        # claims by a deterministic rule — no model call — and the file is then
        # redrawn from them. The redraw is value-identical to what was there,
        # so nothing a reader can observe changes.
        #
        # This block runs LAST for the same reason the v15/v21 blocks do: it
        # imports `timeline`, which reaches `lifehug_core`, whose import BINDS
        # the interpreter to one vault root and refuses an unrepaired vault.
        # The v120 contract repair above must have run first.
        #
        # Idempotent by content, never by a marker file: the flip is skipped
        # when the vault already holds a legacy-import receipt. Vaults that
        # never run `update` heal on their first write instead — see
        # `timeline.save_landmark`.
        try:
            from timeline import flip_landmarks_if_needed  # local import; same dir
            summary = flip_landmarks_if_needed()
            if summary:
                print(
                    f"  Converted {summary['entries']} landmark entr"
                    f"{'y' if summary['entries'] == 1 else 'ies'} into "
                    f"{summary['claims']} temporal claims across "
                    f"{summary['receipts']} receipts; state/landmarks.json is now "
                    f"a projection of them."
                )
        except Exception as exc:  # never let a migration break the update
            print(
                "  Note: landmark projection flip deferred (it will run on the "
                f"next landmark write): {exc}"
            )


def apply_version(version):
    """Apply a specific version by extracting framework files from its tag."""
    tag = f"v{version}"

    # Get framework files list from the TARGET version
    framework_files = get_framework_files_from_tag(version)
    if framework_files is None:
        print(f"Error: Cannot read framework file list from {tag}", file=sys.stderr)
        return False

    current_version = get_local_version()

    # Check for uncommitted changes in framework files
    dirty = check_dirty_framework_files(framework_files)
    if dirty:
        print("Error: The following framework files have uncommitted changes:", file=sys.stderr)
        for f in dirty:
            print(f"  {f}", file=sys.stderr)
        print("\nCommit or stash your changes before updating.", file=sys.stderr)
        return False

    # Extract each framework file from the tag
    updated = []
    skipped = []
    for filepath in framework_files:
        # Special handling: question-bank.md gets saved as upstream copy.
        if filepath == "system/question-bank.md":
            try:
                content = read_repo_file_at(tag, filepath)
                upstream_path = REPO_DIR / "system" / "question-bank-upstream.md"
                upstream_path.write_bytes(content)
                print(f"  Saved upstream question bank to system/question-bank-upstream.md")
            except subprocess.CalledProcessError:
                pass
            continue

        # Never touch protected files
        if is_protected(filepath):
            skipped.append(filepath)
            continue

        try:
            content = read_repo_file_at(tag, filepath)
            target = REPO_DIR / filepath
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(content)
            if repo_file_is_executable_at(tag, filepath):
                target.chmod(target.stat().st_mode | 0o755)
            updated.append(filepath)
        except subprocess.CalledProcessError:
            print(f"  Warning: {filepath} not found in {tag}, skipping", file=sys.stderr)

    # Run any version-specific migrations
    run_migrations(version, current_version)

    if updated:
        # Stage and commit
        for f in updated:
            run_git("add", f)
        # Stage .gitkeep files if they were just created by migrations.
        for marker in (
            "outputs/.gitkeep",
            "sources/manual/.gitkeep",
            "sources/artifacts/.gitkeep",
            "state/.gitkeep",
            "state/roadmap.json",
        ):
            if (REPO_DIR / marker).exists():
                run_git("add", marker, check=False)
        result = subprocess.run(
            ["git", "-C", str(REPO_DIR), "commit", "-m", f"Update Lifehug to v{version}"],
            capture_output=True, text=True,
        )
        if result.returncode != 0:
            # Check if it failed because there was nothing to commit
            if "nothing to commit" in result.stdout or "nothing to commit" in result.stderr:
                print("  Files already match target version — nothing to commit.")
            else:
                print(f"  Warning: git commit failed: {result.stderr.strip()}", file=sys.stderr)
    else:
        print("  All framework files already up to date.")

    return True


def cmd_check(args):
    """Check for available updates.

    Tag-lapse-proof (lifehug#84): compares against BOTH the latest vN tag
    and origin/main's system/version.json. If main is ahead of the latest
    tag, that IS the failure that let v118-v128 ship invisibly for four
    days — update_available reports true off main's version, and a loud
    diagnostic says so, instead of being blinded by the same lapse it's
    meant to catch. A network failure (or no upstream remote) degrades to
    the pre-existing tags-only behavior, silently.
    """
    remote = find_upstream_remote()
    if remote:
        fetch_tags(remote)
    else:
        if not args.quiet:
            print(
                "Warning: No upstream remote found. Tags will be checked locally only.\n"
                "To receive updates, add the upstream remote:\n"
                "  git remote add upstream https://github.com/lifehug/lifehug.git",
                file=sys.stderr,
            )

    current = get_local_version()
    # `latest` keeps its v131 meaning EXACTLY (tags-only) — existing callers
    # (CLAUDE.md's session-start check, any script parsing this JSON) must
    # not silently change behavior. `available_version` is the new,
    # additive "true latest" (tags OR main, whichever is ahead); cards and
    # update_available consume that instead.
    latest = get_latest_version()
    main_info = get_remote_main_info(remote)
    main_version = main_info["version"] if main_info else None
    tag_lapse = main_version is not None and main_version > latest
    available_version = max(latest, main_version) if main_version is not None else latest

    diagnostic = None
    if tag_lapse:
        diagnostic = (
            f"v{main_version} released but not tagged — releases are not "
            "reaching vaults. Tag it to resume delivery."
        )
        print(f"Warning: {diagnostic}", file=sys.stderr)

    update_available = available_version > current

    changelog = None
    if update_available:
        changelog = main_info["changelog"] if tag_lapse else get_tag_changelog(latest)

    result = {
        "current": current,
        "latest": latest,
        "update_available": update_available,
        "changelog": changelog,
        # New fields (lifehug#84) — additive only, existing keys unchanged.
        "main_version": main_version,
        "available_version": available_version,
        "tag_lapse": tag_lapse,
        "diagnostic": diagnostic,
    }
    write_update_check_state(result, args)

    if args.quiet:
        sys.exit(1 if update_available else 0)

    print(json.dumps(result, indent=2))


def cmd_apply(args):
    """Apply an update."""
    remote = find_upstream_remote()
    if remote:
        fetch_tags(remote)
    else:
        print(
            "Warning: No upstream remote found. Using local tags only.\n"
            "To receive updates, add the upstream remote:\n"
            "  git remote add upstream https://github.com/lifehug/lifehug.git",
            file=sys.stderr,
        )

    current = get_local_version()

    if args.version:
        target = args.version
    else:
        target = get_latest_version()

    if target <= 0:
        print("No versions available to apply.")
        return

    if target == current:
        print(f"Already at v{current}. Nothing to update.")
        return

    if target < current:
        print(f"Warning: Downgrading from v{current} to v{target}.")

    print(f"Updating Lifehug from v{current} to v{target}...")

    if apply_version(target):
        print(f"\nLifehug updated to v{target}.")
        changelog = get_tag_changelog(target)
        if changelog:
            print(f"\nChangelog:\n{changelog}")
        # Post-update visibility (lifehug#84 item 4): record every tagged
        # changelog this apply crossed (an apply can jump many releases in
        # one hop) so the viewer can show "what changed" for the update
        # instead of it being a silent file swap.
        write_last_update_state(current, target, collect_crossed_changelogs(current, target), args)
        # The cached --check result's `current` is now stale — without this,
        # the viewer's update card keeps announcing an update that was just
        # installed until someone happens to run --check again.
        refresh_update_check_current(target, args)
    else:
        print("\nUpdate failed.", file=sys.stderr)
        sys.exit(1)


def cmd_rollback(args):
    """Rollback to the previous version."""
    current = get_local_version()
    if current <= 1:
        print("Cannot rollback: already at v1 (initial version).")
        return

    target = current - 1
    print(f"Rolling back from v{current} to v{target}...")

    if apply_version(target):
        print(f"\nRolled back to v{target}.")
        refresh_update_check_current(target, args)
    else:
        print("\nRollback failed.", file=sys.stderr)
        sys.exit(1)


def cmd_migrate_vault(args):
    """Run the v120 vault-contract migration on its own.

    `--apply` already runs it, but a vault that was updated before this
    migration existed is stuck: its framework files are current and every
    entry point refuses to bind it. This is the way out.

    Target resolution honors the same escape hatches as the rest of the CLI:
    --vault-root, then LIFEHUG_VAULT_ROOT, then this checkout (REPO_DIR) —
    the whole point of this command is repairing a vault the loader refuses,
    so it must not silently migrate the wrong tree and report success.
    """
    root = getattr(args, "vault_root", None) or os.environ.get("LIFEHUG_VAULT_ROOT")
    repo = Path(root).expanduser() if root else REPO_DIR
    if not repo.is_dir():
        print(f"Error: vault root {repo} is not a directory", file=sys.stderr)
        return 1
    try:
        changed = migrate_vault_to_v120(repo)
    except Exception as exc:  # a broken vault is exactly who runs this
        print(f"Error: migration failed: {exc}", file=sys.stderr)
        print("No files were rebuilt without a .pre-v120 salvage copy.", file=sys.stderr)
        return 1
    if changed:
        print(f"Migrated {len(changed)} durable-data file(s) in {repo} to the v120 vault contract:")
        for path in changed:
            print(f"  {path}")
    else:
        print(f"Vault at {repo} already satisfies the v120 durable-data contract. Nothing to do.")
    return 0


def main():
    parser = argparse.ArgumentParser(description="Lifehug update manager")
    parser.add_argument("--check", action="store_true", help="Check for updates")
    parser.add_argument("--quiet", action="store_true", help="Exit code only (with --check)")
    parser.add_argument("--apply", action="store_true", help="Apply latest update")
    parser.add_argument("--version", type=int, metavar="N", help="Target version (with --apply)")
    parser.add_argument("--rollback", action="store_true", help="Rollback to previous version")
    parser.add_argument(
        "--vault-root", metavar="PATH", default=None,
        help="Vault to operate on with --migrate-vault, and where --check/"
             "--apply/--rollback cache their state (default: "
             "LIFEHUG_VAULT_ROOT, then this checkout)",
    )
    parser.add_argument(
        "--migrate-vault", action="store_true",
        help="Repair a pre-v120 vault against the v120 durable-data contract "
             "(idempotent; safe to run on an already-current vault)",
    )
    args = parser.parse_args()

    if args.check:
        cmd_check(args)
    elif args.apply:
        cmd_apply(args)
    elif args.rollback:
        cmd_rollback(args)
    elif args.migrate_vault:
        sys.exit(cmd_migrate_vault(args) or 0)
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
